
// To check if a library is compiled with CocoaPods you
// can use the `COCOAPODS` macro definition which is
// defined in the xcconfigs so it is available in
// headers also when they are imported in the client
// project.


// AFNetworking
#define COCOAPODS_POD_AVAILABLE_AFNetworking
#define COCOAPODS_VERSION_MAJOR_AFNetworking 2
#define COCOAPODS_VERSION_MINOR_AFNetworking 3
#define COCOAPODS_VERSION_PATCH_AFNetworking 1

// AFNetworking/NSURLConnection
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLConnection
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLConnection 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLConnection 3
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLConnection 1

// AFNetworking/NSURLSession
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLSession
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLSession 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLSession 3
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLSession 1

// AFNetworking/Reachability
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Reachability
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Reachability 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Reachability 3
#define COCOAPODS_VERSION_PATCH_AFNetworking_Reachability 1

// AFNetworking/Security
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Security
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Security 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Security 3
#define COCOAPODS_VERSION_PATCH_AFNetworking_Security 1

// AFNetworking/Serialization
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Serialization
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Serialization 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Serialization 3
#define COCOAPODS_VERSION_PATCH_AFNetworking_Serialization 1

// BlocksKit
#define COCOAPODS_POD_AVAILABLE_BlocksKit
#define COCOAPODS_VERSION_MAJOR_BlocksKit 2
#define COCOAPODS_VERSION_MINOR_BlocksKit 2
#define COCOAPODS_VERSION_PATCH_BlocksKit 2

// BlocksKit/All
#define COCOAPODS_POD_AVAILABLE_BlocksKit_All
#define COCOAPODS_VERSION_MAJOR_BlocksKit_All 2
#define COCOAPODS_VERSION_MINOR_BlocksKit_All 2
#define COCOAPODS_VERSION_PATCH_BlocksKit_All 2

// BlocksKit/Core
#define COCOAPODS_POD_AVAILABLE_BlocksKit_Core
#define COCOAPODS_VERSION_MAJOR_BlocksKit_Core 2
#define COCOAPODS_VERSION_MINOR_BlocksKit_Core 2
#define COCOAPODS_VERSION_PATCH_BlocksKit_Core 2

// BlocksKit/DynamicDelegate
#define COCOAPODS_POD_AVAILABLE_BlocksKit_DynamicDelegate
#define COCOAPODS_VERSION_MAJOR_BlocksKit_DynamicDelegate 2
#define COCOAPODS_VERSION_MINOR_BlocksKit_DynamicDelegate 2
#define COCOAPODS_VERSION_PATCH_BlocksKit_DynamicDelegate 2

// ReactiveCocoa
#define COCOAPODS_POD_AVAILABLE_ReactiveCocoa
#define COCOAPODS_VERSION_MAJOR_ReactiveCocoa 2
#define COCOAPODS_VERSION_MINOR_ReactiveCocoa 0
#define COCOAPODS_VERSION_PATCH_ReactiveCocoa 0

// ReactiveCocoa/Core
#define COCOAPODS_POD_AVAILABLE_ReactiveCocoa_Core
#define COCOAPODS_VERSION_MAJOR_ReactiveCocoa_Core 2
#define COCOAPODS_VERSION_MINOR_ReactiveCocoa_Core 0
#define COCOAPODS_VERSION_PATCH_ReactiveCocoa_Core 0

// ReactiveCocoa/RACExtensions
#define COCOAPODS_POD_AVAILABLE_ReactiveCocoa_RACExtensions
#define COCOAPODS_VERSION_MAJOR_ReactiveCocoa_RACExtensions 2
#define COCOAPODS_VERSION_MINOR_ReactiveCocoa_RACExtensions 0
#define COCOAPODS_VERSION_PATCH_ReactiveCocoa_RACExtensions 0

// ReactiveCocoa/no-arc
#define COCOAPODS_POD_AVAILABLE_ReactiveCocoa_no_arc
#define COCOAPODS_VERSION_MAJOR_ReactiveCocoa_no_arc 2
#define COCOAPODS_VERSION_MINOR_ReactiveCocoa_no_arc 0
#define COCOAPODS_VERSION_PATCH_ReactiveCocoa_no_arc 0

