
// To check if a library is compiled with CocoaPods you
// can use the `COCOAPODS` macro definition which is
// defined in the xcconfigs so it is available in
// headers also when they are imported in the client
// project.


// AFNetworking
#define COCOAPODS_POD_AVAILABLE_AFNetworking
#define COCOAPODS_VERSION_MAJOR_AFNetworking 2
#define COCOAPODS_VERSION_MINOR_AFNetworking 3
#define COCOAPODS_VERSION_PATCH_AFNetworking 1

// AFNetworking/NSURLConnection
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLConnection
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLConnection 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLConnection 3
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLConnection 1

// AFNetworking/NSURLSession
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLSession
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLSession 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLSession 3
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLSession 1

// AFNetworking/Reachability
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Reachability
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Reachability 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Reachability 3
#define COCOAPODS_VERSION_PATCH_AFNetworking_Reachability 1

// AFNetworking/Security
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Security
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Security 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Security 3
#define COCOAPODS_VERSION_PATCH_AFNetworking_Security 1

// AFNetworking/Serialization
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Serialization
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Serialization 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Serialization 3
#define COCOAPODS_VERSION_PATCH_AFNetworking_Serialization 1

// AFNetworking/UIKit
#define COCOAPODS_POD_AVAILABLE_AFNetworking_UIKit
#define COCOAPODS_VERSION_MAJOR_AFNetworking_UIKit 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_UIKit 3
#define COCOAPODS_VERSION_PATCH_AFNetworking_UIKit 1

// Appirater
#define COCOAPODS_POD_AVAILABLE_Appirater
#define COCOAPODS_VERSION_MAJOR_Appirater 0
#define COCOAPODS_VERSION_MINOR_Appirater 0
#define COCOAPODS_VERSION_PATCH_Appirater 4

// BlocksKit
#define COCOAPODS_POD_AVAILABLE_BlocksKit
#define COCOAPODS_VERSION_MAJOR_BlocksKit 2
#define COCOAPODS_VERSION_MINOR_BlocksKit 2
#define COCOAPODS_VERSION_PATCH_BlocksKit 2

// BlocksKit/All
#define COCOAPODS_POD_AVAILABLE_BlocksKit_All
#define COCOAPODS_VERSION_MAJOR_BlocksKit_All 2
#define COCOAPODS_VERSION_MINOR_BlocksKit_All 2
#define COCOAPODS_VERSION_PATCH_BlocksKit_All 2

// BlocksKit/Core
#define COCOAPODS_POD_AVAILABLE_BlocksKit_Core
#define COCOAPODS_VERSION_MAJOR_BlocksKit_Core 2
#define COCOAPODS_VERSION_MINOR_BlocksKit_Core 2
#define COCOAPODS_VERSION_PATCH_BlocksKit_Core 2

// BlocksKit/DynamicDelegate
#define COCOAPODS_POD_AVAILABLE_BlocksKit_DynamicDelegate
#define COCOAPODS_VERSION_MAJOR_BlocksKit_DynamicDelegate 2
#define COCOAPODS_VERSION_MINOR_BlocksKit_DynamicDelegate 2
#define COCOAPODS_VERSION_PATCH_BlocksKit_DynamicDelegate 2

// BlocksKit/MessageUI
#define COCOAPODS_POD_AVAILABLE_BlocksKit_MessageUI
#define COCOAPODS_VERSION_MAJOR_BlocksKit_MessageUI 2
#define COCOAPODS_VERSION_MINOR_BlocksKit_MessageUI 2
#define COCOAPODS_VERSION_PATCH_BlocksKit_MessageUI 2

// BlocksKit/UIKit
#define COCOAPODS_POD_AVAILABLE_BlocksKit_UIKit
#define COCOAPODS_VERSION_MAJOR_BlocksKit_UIKit 2
#define COCOAPODS_VERSION_MINOR_BlocksKit_UIKit 2
#define COCOAPODS_VERSION_PATCH_BlocksKit_UIKit 2

// GHUnitIOS
#define COCOAPODS_POD_AVAILABLE_GHUnitIOS
#define COCOAPODS_VERSION_MAJOR_GHUnitIOS 0
#define COCOAPODS_VERSION_MINOR_GHUnitIOS 5
#define COCOAPODS_VERSION_PATCH_GHUnitIOS 6

// HockeySDK
#define COCOAPODS_POD_AVAILABLE_HockeySDK
#define COCOAPODS_VERSION_MAJOR_HockeySDK 3
#define COCOAPODS_VERSION_MINOR_HockeySDK 5
#define COCOAPODS_VERSION_PATCH_HockeySDK 7

// NSLogger
#define COCOAPODS_POD_AVAILABLE_NSLogger
#define COCOAPODS_VERSION_MAJOR_NSLogger 1
#define COCOAPODS_VERSION_MINOR_NSLogger 1
#define COCOAPODS_VERSION_PATCH_NSLogger 0

// PureLayout
#define COCOAPODS_POD_AVAILABLE_PureLayout
#define COCOAPODS_VERSION_MAJOR_PureLayout 1
#define COCOAPODS_VERSION_MINOR_PureLayout 1
#define COCOAPODS_VERSION_PATCH_PureLayout 0

// RMStore
#define COCOAPODS_POD_AVAILABLE_RMStore
#define COCOAPODS_VERSION_MAJOR_RMStore 0
#define COCOAPODS_VERSION_MINOR_RMStore 4
#define COCOAPODS_VERSION_PATCH_RMStore 2

// RMStore/AppReceiptVerificator
#define COCOAPODS_POD_AVAILABLE_RMStore_AppReceiptVerificator
#define COCOAPODS_VERSION_MAJOR_RMStore_AppReceiptVerificator 0
#define COCOAPODS_VERSION_MINOR_RMStore_AppReceiptVerificator 4
#define COCOAPODS_VERSION_PATCH_RMStore_AppReceiptVerificator 2

// RMStore/Core
#define COCOAPODS_POD_AVAILABLE_RMStore_Core
#define COCOAPODS_VERSION_MAJOR_RMStore_Core 0
#define COCOAPODS_VERSION_MINOR_RMStore_Core 4
#define COCOAPODS_VERSION_PATCH_RMStore_Core 2

// RMStore/KeychainPersistence
#define COCOAPODS_POD_AVAILABLE_RMStore_KeychainPersistence
#define COCOAPODS_VERSION_MAJOR_RMStore_KeychainPersistence 0
#define COCOAPODS_VERSION_MINOR_RMStore_KeychainPersistence 4
#define COCOAPODS_VERSION_PATCH_RMStore_KeychainPersistence 2

// RMStore/NSUserDefaultsPersistence
#define COCOAPODS_POD_AVAILABLE_RMStore_NSUserDefaultsPersistence
#define COCOAPODS_VERSION_MAJOR_RMStore_NSUserDefaultsPersistence 0
#define COCOAPODS_VERSION_MINOR_RMStore_NSUserDefaultsPersistence 4
#define COCOAPODS_VERSION_PATCH_RMStore_NSUserDefaultsPersistence 2

// RMStore/OpenSSL
#define COCOAPODS_POD_AVAILABLE_RMStore_OpenSSL
#define COCOAPODS_VERSION_MAJOR_RMStore_OpenSSL 0
#define COCOAPODS_VERSION_MINOR_RMStore_OpenSSL 4
#define COCOAPODS_VERSION_PATCH_RMStore_OpenSSL 2

// RMStore/TransactionReceiptVerificator
#define COCOAPODS_POD_AVAILABLE_RMStore_TransactionReceiptVerificator
#define COCOAPODS_VERSION_MAJOR_RMStore_TransactionReceiptVerificator 0
#define COCOAPODS_VERSION_MINOR_RMStore_TransactionReceiptVerificator 4
#define COCOAPODS_VERSION_PATCH_RMStore_TransactionReceiptVerificator 2

// Reachability
#define COCOAPODS_POD_AVAILABLE_Reachability
#define COCOAPODS_VERSION_MAJOR_Reachability 3
#define COCOAPODS_VERSION_MINOR_Reachability 1
#define COCOAPODS_VERSION_PATCH_Reachability 1

// ReactiveCocoa
#define COCOAPODS_POD_AVAILABLE_ReactiveCocoa
#define COCOAPODS_VERSION_MAJOR_ReactiveCocoa 2
#define COCOAPODS_VERSION_MINOR_ReactiveCocoa 0
#define COCOAPODS_VERSION_PATCH_ReactiveCocoa 0

// ReactiveCocoa/Core
#define COCOAPODS_POD_AVAILABLE_ReactiveCocoa_Core
#define COCOAPODS_VERSION_MAJOR_ReactiveCocoa_Core 2
#define COCOAPODS_VERSION_MINOR_ReactiveCocoa_Core 0
#define COCOAPODS_VERSION_PATCH_ReactiveCocoa_Core 0

// ReactiveCocoa/RACExtensions
#define COCOAPODS_POD_AVAILABLE_ReactiveCocoa_RACExtensions
#define COCOAPODS_VERSION_MAJOR_ReactiveCocoa_RACExtensions 2
#define COCOAPODS_VERSION_MINOR_ReactiveCocoa_RACExtensions 0
#define COCOAPODS_VERSION_PATCH_ReactiveCocoa_RACExtensions 0

// ReactiveCocoa/no-arc
#define COCOAPODS_POD_AVAILABLE_ReactiveCocoa_no_arc
#define COCOAPODS_VERSION_MAJOR_ReactiveCocoa_no_arc 2
#define COCOAPODS_VERSION_MINOR_ReactiveCocoa_no_arc 0
#define COCOAPODS_VERSION_PATCH_ReactiveCocoa_no_arc 0

// SSKeychain
#define COCOAPODS_POD_AVAILABLE_SSKeychain
#define COCOAPODS_VERSION_MAJOR_SSKeychain 1
#define COCOAPODS_VERSION_MINOR_SSKeychain 2
#define COCOAPODS_VERSION_PATCH_SSKeychain 1

// SocketRocket
#define COCOAPODS_POD_AVAILABLE_SocketRocket
#define COCOAPODS_VERSION_MAJOR_SocketRocket 0
#define COCOAPODS_VERSION_MINOR_SocketRocket 3
#define COCOAPODS_VERSION_PATCH_SocketRocket 1

// SocketShuttle
#define COCOAPODS_POD_AVAILABLE_SocketShuttle
#define COCOAPODS_VERSION_MAJOR_SocketShuttle 0
#define COCOAPODS_VERSION_MINOR_SocketShuttle 5
#define COCOAPODS_VERSION_PATCH_SocketShuttle 1

